# Generated by Django 5.2.6 on 2025-10-03 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='diary',
            name='note',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='diary',
            table='diary',
        ),
    ]
