# Generated by Django 5.2.6 on 2025-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_diary_data_diary_note_alter_diary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='week',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], default=1),
        ),
    ]
